### ISSUE TITLE
How to support patching AGB_FIRM?

### ISSUE THREAD

**Issue by jo32** [mid-kid/CakesForeveryWan#14] opened 2016-01-18 17:38 UTC
I built the newest code and placed files downloaded from https://github.com/mid-kid/CakesForeveryWan/blob/master/agb_firmurl named agb_firmware.bin and agb_cetk, it boot well on my new 3ds, but I still cannot play gba vc game. BTW, patched 0004013800000202.bin is not install on  my emunand and sysnand.

**Comment by mid-kid** [comment] 2016-01-18 19:06
There's no patches for AGB_FIRM, nor is there a reboot patch that boots into AGB_FIRM yet. I won't be looking into this in a bit (Implemented due to the possibility of people wanting to screw around with it).
Closing because this works as intended.

**Closed as completed by mid-kid** 2016-01-18 19:06 UTC
Labels: Works as intended
