### ISSUE TITLE
I'm not able to load RedNAND

### ISSUE THREAD

**Issue by SuryaKmuar** [mid-kid/CakesForeveryWan#52] opened 2016-05-07 09:01 UTC

**Comment by socram8888** [comment] 2016-05-07 09:14
This is Cakes CFW issue tracker, not Luma3DS'

If you are having a problem with booting into EmuNAND you should ask either on https://github.com/Plailect/Guide/issues or https://github.com/AuroraWright/Luma3DS.

**Comment by SuryaKmuar** [comment] 2016-05-07 10:05
sorry i was irritated so i posted here without knowing this is for cakes CFW issue tracker.
BTW thanks

**Comment by mid-kid** [comment] 2016-05-07 11:51
If the issue is wrong/incorrect and you don't need any more help here, please consider closing the issue yourself next time. Thanks.

**Closed as completed by mid-kid** 2016-05-07 11:51 UTC
