### ISSUE TITLE
Emunand detection failed in 2ds, release 85

### ISSUE THREAD

**Issue by b1l1s** [mid-kid/CakesForeveryWan#8] opened 2015-08-16 17:01 UTC
As reported by [thaikoa](http://gbatemp.net/threads/release-cakesfw.391200/page-42#post-5618917)

**Comment by b1l1s** [comment] 2015-08-17 03:23
NAND CSD data :

```
40 40 8A E7 FF DB F6 6B 02 5A 0F 32 01 27 D0 00
```

Gives the size of ~1.21GB using @Normmatt's method. thaikoa also reported that his nand dump from GW is 1.21GB in size, while the one from Decrypt9 is 943MB in size.

He's using the nand dump from Decrypt9 which explains why we failed to detect it.

**Comment by Normmatt** [comment] 2015-08-17 03:40
That's because Decrypt9 doesn't dump the entire nand like it should.

**Comment by b1l1s** [comment] 2015-08-17 05:04
@Normmatt agreed.

So we have two options so far:
1. Integrate a rednand formatter - which means that CakesFW emunand will be incompatible with other CFWs.
2. Leave it as it is - some 2DSes will be incompatible with our/other CFWs, depending on which dump they use.

I'm going to leave this open until @mid-kid can chime in. Maybe there's another way to work around this.

**Comment by mid-kid** [comment] 2015-08-17 12:29
A malformed/incomplete NAND dump is a bad dump. No way around that.
We won't support loading a Toshiba NAND when it's clear you have a N3DS Samsung NAND on your 2DS.

The problem is, Decrypt9 and rxTools hard-code their NAND sizes, and since this console isn't detected as a N3DS, it uses a size too small. This gives a problem, since you can't boot rxTools with a GW-formatted emuNAND (GW detects it the right way), if you have this type of NAND. This is probably why this person created his emuNAND with a NAND dump from Decrypt9.

I believe this is a wontfix for this project. Other projects should fix up their stuff to get the correct NAND sizes.

**Closed as completed by mid-kid** 2015-08-17 12:29 UTC
Labels: wontfix

**Comment by mid-kid** [comment] 2015-08-17 12:33
Also, it isn't a bug, it's a feature. :P
